version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - sqlclosecheck
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Tx).Rollback
        - github.com/BleKuntay/FlipChat/backend/pkg/logger.Sync
        - (*github.com/golang-migrate/migrate/v4.Migrate).Close