name: Backend CI

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'backend/**'

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: backend/go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go mod download
      - name: Run unit tests
        run: go test -v -json ./... > TestResults-unit.json
      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Go-results-unit
          path: backend/TestResults-unit.json

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: backend/go.sum
      - name: Install dependencies
        run: go mod download
      - name: Run integration tests
        run: go test -v -json -tags integration ./... > TestResults-integration.json
      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Go-results-integration
          path: backend/TestResults-integration.json